databases:
  - name: microbudget
    databaseName: microbudget
    user: microbudget_user

services:
  - type: web
    name: jamie
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name:microbudget
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
